# Generated by Django 2.2.7 on 2020-04-19 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('O', 'Ordered'), ('D', 'Delivering'), ('C', 'Completed')], default='O', max_length=1),
        ),
    ]
