# Generated by Django 2.2.7 on 2020-04-21 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_is_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('O', 'Ordered'), ('M', 'Making'), ('D', 'Delivering'), ('C', 'Completed')], default='O', max_length=1),
        ),
    ]
